# Generated by Django 6.0.1 on 2026-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='desired_role',
            field=models.CharField(choices=[('CASHIER', 'Cashier'), ('SHOP_ADMIN', 'Shop Administrator'), ('SITE_ADMIN', 'Site Administrator')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SITE_ADMIN', 'Site Administrator'), ('SHOP_ADMIN', 'Shop Administrator'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=15),
        ),
    ]
