# Generated by Django 6.0.1 on 2026-01-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_registrationrequest_desired_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop_admin',
            field=models.ForeignKey(blank=True, help_text='Shop Admin this cashier belongs to', limit_choices_to={'role': 'SHOP_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Business/Shop name for Shop Admins', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SITE_ADMIN', 'Site Administrator'), ('SHOP_ADMIN', 'Shop Administrator'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
