# Generated by Django 6.0.1 on 2026-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shop_address',
            field=models.CharField(blank=True, help_text='Business address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_city',
            field=models.CharField(blank=True, help_text='Business city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_email',
            field=models.EmailField(blank=True, help_text='Business email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shop_phone',
            field=models.CharField(blank=True, help_text='Business phone', max_length=20, null=True),
        ),
    ]
