# Generated by Django 6.0.1 on 2026-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_signature",
            field=models.ImageField(
                blank=True,
                help_text="Customer signature for delivered orders",
                null=True,
                upload_to="signatures/",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when order was signed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("SIGNED", "Signed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
