# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoicing.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_update_existing_sales_shop_admin'),
        ('products', '0002_product_shop_admin'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True, default='Payment due within 30 days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=invoicing.models.invoice_pdf_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='auth.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.customer')),
                ('shop_admin', models.ForeignKey(limit_choices_to={'role': 'SHOP_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['shop_admin', 'status'], name='invoicing_invoice_shop_admin_status_idx'),
                    models.Index(fields=['customer', 'status'], name='invoicing_invoice_customer_status_idx'),
                    models.Index(fields=['invoice_number'], name='invoicing_invoice_invoice_number_idx'),
                    models.Index(fields=['due_date'], name='invoicing_invoice_due_date_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('header_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#1f2937', help_text='Primary color in hex format', max_length=7)),
                ('secondary_color', models.CharField(default='#6b7280', help_text='Secondary color in hex format', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_admin', models.ForeignKey(limit_choices_to={'role': 'SHOP_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='users.userprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('shop_admin', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Custom description (overrides product name if provided)', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, help_text='Discount rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('invoice', 'product')},
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('CHECK', 'Check'), ('OTHER', 'Other')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='auth.user')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['invoice', 'created_at'], name='invoicing_invoice_payment_invoice_created_at_idx'),
                    models.Index(fields=['payment_method'], name='invoicing_invoice_payment_payment_method_idx'),
                ],
            },
        ),
    ]
