# Generated by Django 6.0.1 on 2026-02-01 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_shop_ad_dca2f9_idx",
            old_name="invoicing_invoice_shop_admin_status_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_custome_f28b76_idx",
            old_name="invoicing_invoice_customer_status_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_invoice_f2b05e_idx",
            old_name="invoicing_invoice_invoice_number_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_due_dat_92e42f_idx",
            old_name="invoicing_invoice_due_date_idx",
        ),
        migrations.RenameIndex(
            model_name="invoicepayment",
            new_name="invoicing_i_invoice_e0a318_idx",
            old_name="invoicing_invoice_payment_invoice_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="invoicepayment",
            new_name="invoicing_i_payment_0f63e3_idx",
            old_name="invoicing_invoice_payment_payment_method_idx",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax rate in percentage",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoicepayment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="footer_text",
            field=models.TextField(
                blank=True, help_text="Custom footer text for invoices"
            ),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="header_text",
            field=models.TextField(
                blank=True, help_text="Custom header text for invoices"
            ),
        ),
        migrations.AlterField(
            model_name="invoicetemplate",
            name="terms_conditions",
            field=models.TextField(blank=True, help_text="Terms and conditions"),
        ),
    ]
