# Generated by Django 6.0.1 on 2026-01-31 11:39

from django.db import migrations


def set_default_shop_admin_for_existing_data(apps, schema_editor):
    """
    Set a default shop admin for existing sales and products that have NULL shop_admin.
    This migration finds the first shop admin and assigns them to existing records.
    """
    Sale = apps.get_model('sales', 'Sale')
    UserProfile = apps.get_model('users', 'UserProfile')
    Product = apps.get_model('products', 'Product')
    
    # Find the first shop admin
    first_shop_admin = UserProfile.objects.filter(role='SHOP_ADMIN').first()
    
    if first_shop_admin:
        # Update existing sales with NULL shop_admin
        Sale.objects.filter(shop_admin__isnull=True).update(shop_admin=first_shop_admin)
        
        # Update existing products with NULL shop_admin
        Product.objects.filter(shop_admin__isnull=True).update(shop_admin=first_shop_admin)


def reverse_set_default_shop_admin_for_existing_data(apps, schema_editor):
    """
    Reverse the migration by setting shop_admin to NULL for existing records.
    """
    Sale = apps.get_model('sales', 'Sale')
    Product = apps.get_model('products', 'Product')
    
    # Set shop_admin back to NULL for records that were updated
    Sale.objects.filter(shop_admin__isnull=False).update(shop_admin=None)
    Product.objects.filter(shop_admin__isnull=False).update(shop_admin=None)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_shop_admin"),
        ("products", "0002_product_shop_admin"),
    ]

    operations = [
        migrations.RunPython(
            set_default_shop_admin_for_existing_data,
            reverse_set_default_shop_admin_for_existing_data
        ),
    ]
