# Generated by Django 6.0.1 on 2026-01-31 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0006_userprofile_shop_address_userprofile_shop_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop_admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "SHOP_ADMIN"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="users.userprofile",
            ),
        ),
    ]
